version: '3'
services:
  wsgi-server:
    build:
      context: .
      target: wsgi-server-base
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      APP_DOMAIN: localhost:9000
      WORKER_TIMEOUT: 180
      DJANGO_SUPERUSER_USERNAME: admin # default superuser name
      DJANGO_SUPERUSER_PASSWORD: password # default superuser password
      DJANGO_SUPERUSER_EMAIL: admin@example.com # default superuser email
      ACCOUNT_EMAIL_VERIFICATION: ${ACCOUNT_EMAIL_VERIFICATION:-none} # Determines the e-mail verification method during signup – choose one of "none", "optional", or "mandatory". Default is "optional". If you don't need to verify the email, you can set it to "none".
      DB_URL: ${DB_URL:-sqlite:///db.sqlite3}
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    networks:
      - chatgpt-ui-network
  web-server:
    build:
      context: .
    environment:
      - BACKEND_URL=http://wsgi-server:8000
    ports:
      - '9000:80'
    depends_on:
      - wsgi-server
    networks:
      - chatgpt-ui-network

networks:
  chatgpt-ui-network:
    external: true